# Generated by Django 2.1.4 on 2018-12-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='relation',
            new_name='relationdd',
        ),
    ]
