# Generated by Django 2.1.4 on 2018-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profiles_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='photo',
            field=models.FileField(default='', upload_to='upload'),
        ),
    ]
